FROM eclipse-temurin:21-jre-noble

RUN groupadd --system app && useradd --system --gid app app
WORKDIR /app
COPY --from=artifact --chown=app:app collab-docs-backend-0.0.1-SNAPSHOT-exec.jar app.jar
USER app

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
