CREATE TABLE IF NOT EXISTS copage_group (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(80) NOT NULL,
 description VARCHAR(300) NOT NULL DEFAULT '', owner_id BIGINT NOT NULL,
 is_archived TINYINT NOT NULL DEFAULT 0,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY idx_group_owner(owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS group_member (
 group_id BIGINT NOT NULL, user_id BIGINT NOT NULL, role VARCHAR(10) NOT NULL,
 joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(group_id,user_id), KEY idx_group_member_user(user_id,group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS group_invitation (
 group_id BIGINT NOT NULL, user_id BIGINT NOT NULL, inviter_id BIGINT NOT NULL,
 status VARCHAR(12) NOT NULL DEFAULT 'pending', invitation_version BIGINT NOT NULL DEFAULT 1,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(group_id,user_id), KEY idx_group_invitation_user(user_id,status,group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
